rule:
  meta:
    name: capture network configuration via ifconfig
    namespace: collection/network
    authors:
      - joakim@intezeer.com
    scopes:
      static: basic block
      dynamic: call
    att&ck:
      - Discovery::System Network Configuration Discovery [T1016]
  features:
    - and:
      - os: linux
      - api: system
      - substring: "ifconfig"
